# Generated by Django 4.1.1 on 2022-10-06 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datagov", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonGov60",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nnid", models.CharField(max_length=50, verbose_name="nnid")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("f_name", models.CharField(max_length=200, verbose_name="f_name")),
                ("l_name", models.CharField(max_length=200, verbose_name="l_name")),
                (
                    "birth_date",
                    models.CharField(
                        max_length=100, null=True, verbose_name="birth_date"
                    ),
                ),
                ("sex", models.CharField(max_length=50, null=True, verbose_name="sex")),
                (
                    "body_code",
                    models.CharField(max_length=2, null=True, verbose_name="body_code"),
                ),
            ],
            options={
                "verbose_name": "PersonGov60",
                "verbose_name_plural": "PersonGov60s",
            },
        ),
        migrations.CreateModel(
            name="PersonHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_code",
                    models.CharField(max_length=20, verbose_name="house_code"),
                ),
                (
                    "house_addr",
                    models.CharField(max_length=20, verbose_name="house_addr"),
                ),
            ],
            options={
                "verbose_name": "PersonHouse",
                "verbose_name_plural": "PersonHouses",
            },
        ),
        migrations.DeleteModel(name="gov_nid",),
        migrations.AddField(
            model_name="persongov60",
            name="house_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="datagov.personhouse"
            ),
        ),
    ]
