# Generated by Django 4.1.1 on 2022-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagov", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gov_nid",
            name="house_code",
            field=models.CharField(max_length=20, null=True, verbose_name="house_code"),
        ),
    ]
