# Generated by Django 4.1.1 on 2022-10-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagov", "0003_alter_persongov60_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persongov60",
            name="body_code",
            field=models.CharField(max_length=2, null=True, verbose_name="bodycode"),
        ),
        migrations.AlterField(
            model_name="persongov60",
            name="f_name",
            field=models.CharField(max_length=200, verbose_name="fristname"),
        ),
        migrations.AlterField(
            model_name="persongov60",
            name="l_name",
            field=models.CharField(max_length=200, verbose_name="lastname"),
        ),
        migrations.AlterField(
            model_name="personhouse",
            name="house_addr",
            field=models.CharField(max_length=20, verbose_name="houseaddr"),
        ),
        migrations.AlterField(
            model_name="personhouse",
            name="house_code",
            field=models.CharField(max_length=20, verbose_name="housecode"),
        ),
    ]
