# Generated by Django 4.1.1 on 2022-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagov", "0006_alter_persongov60_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personhouse",
            name="house_addr",
            field=models.CharField(max_length=20, verbose_name="House addr"),
        ),
        migrations.AlterField(
            model_name="personhouse",
            name="house_code",
            field=models.IntegerField(max_length=20, verbose_name="House code"),
        ),
    ]
