# Generated by Django 4.1.1 on 2022-10-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagov", "0007_alter_personhouse_house_addr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personhouse",
            name="house_addr",
            field=models.CharField(max_length=50, verbose_name="House addr"),
        ),
        migrations.AlterField(
            model_name="personhouse",
            name="house_code",
            field=models.IntegerField(verbose_name="House code"),
        ),
    ]
